/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *SignIn;
    QGroupBox *groupBox;
    QLabel *label_username;
    QLabel *label_password;
    QLineEdit *lineEdit_username;
    QLineEdit *lineEdit_password;
    QPushButton *pushButton_login;
    QLabel *label_status;
    QLabel *label_status_2;
    QWidget *AdminBase;
    QGroupBox *groupBox_2;
    QPushButton *pushButton_members;
    QPushButton *pushButton_inventory;
    QPushButton *pushButton_memberships;
    QPushButton *pushButton_logout_admin;
    QPushButton *pushButton_purchase;
    QWidget *ManagerBase;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_sales;
    QPushButton *pushButton_purchases;
    QPushButton *pushButton_qty;
    QPushButton *pushButton_rebates;
    QPushButton *pushButton_expirations;
    QPushButton *pushButton_item_lookup;
    QPushButton *pushButton_member_lookup;
    QPushButton *pushButton_convert;
    QPushButton *pushButton_logout_manager;
    QWidget *ManagerMembers;
    QGroupBox *groupBox_4;
    QPushButton *pushButton_back;
    QPushButton *addMemberButton;
    QPushButton *pushButton_4;
    QTableView *tableView_8;
    QWidget *ManageInventory;
    QGroupBox *groupBox_5;
    QPushButton *pushButton_back_inventory;
    QPushButton *pushButton_addItem;
    QPushButton *pushButton_removeItem;
    QTableView *tableView_9;
    QWidget *ManageMemberships;
    QGroupBox *groupBox_6;
    QPushButton *pushButton_back_memberships;
    QWidget *SalesReport;
    QGroupBox *groupBox_7;
    QPushButton *pushButton_back_report;
    QLabel *label_14;
    QLineEdit *date_edit;
    QPushButton *pushButton_9;
    QTableView *tableView_4;
    QLabel *label_15;
    QDoubleSpinBox *totalrevenue;
    QLabel *label_16;
    QSpinBox *executive;
    QLabel *label_17;
    QSpinBox *regular;
    QPushButton *pushButton_12;
    QTableView *tableView_10;
    QPushButton *pushButton_16;
    QWidget *TotPurchasesByNum;
    QGroupBox *groupBox_8;
    QPushButton *pushButton_back_purchases;
    QPushButton *LoadData;
    QTableView *tableView;
    QLabel *label_9;
    QDoubleSpinBox *total;
    QWidget *QtySold;
    QGroupBox *groupBox_9;
    QPushButton *pushButton_back_qty;
    QLineEdit *searchBox;
    QLabel *label_21;
    QPushButton *pushButton_13;
    QLabel *label_23;
    QLabel *label_24;
    QSpinBox *qty;
    QDoubleSpinBox *revenue_3;
    QWidget *Rebates;
    QGroupBox *groupBox_10;
    QPushButton *pushButton_back_rebates;
    QTableView *tableView_6;
    QPushButton *pushButton_11;
    QWidget *MembExp;
    QGroupBox *groupBox_11;
    QPushButton *pushButton_back_expirations;
    QLabel *label_18;
    QLineEdit *month;
    QTableView *tableView_5;
    QLabel *label_19;
    QLabel *label_20;
    QTextBrowser *textBrowser;
    QTextBrowser *textBrowser_2;
    QPushButton *pushButton_10;
    QListWidget *listWidget;
    QListWidget *listWidget_2;
    QListWidget *listWidget_3;
    QWidget *ItemLookup;
    QGroupBox *groupBox_12;
    QPushButton *pushButton_back_item_lookup;
    QLabel *label_11;
    QLineEdit *item_edit;
    QPushButton *pushButton_8;
    QTableView *tableView_3;
    QDoubleSpinBox *revenue;
    QLabel *label_12;
    QLabel *label_13;
    QSpinBox *sold;
    QWidget *MemberLookup;
    QGroupBox *groupBox_13;
    QPushButton *pushButton_back_member_lookup;
    QLineEdit *search_edit;
    QLabel *label_10;
    QTableView *tableView_2;
    QPushButton *pushButton_7;
    QWidget *ConvertMembership;
    QGroupBox *groupBox_14;
    QPushButton *pushButton_back_convert;
    QPushButton *SearchMembUpgrade;
    QPushButton *SearchMembDowngrade;
    QWidget *AddItem;
    QGroupBox *groupBox_15;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *item;
    QLabel *label;
    QLineEdit *itemName;
    QWidget *verticalLayoutWidget_2;
    QVBoxLayout *verticalLayout;
    QLabel *label_2;
    QDoubleSpinBox *addItemPrice;
    QLabel *message;
    QPushButton *pushButton;
    QPushButton *pushButton_5;
    QWidget *RemoveItem;
    QGroupBox *groupBox_16;
    QWidget *verticalLayoutWidget_3;
    QVBoxLayout *item_2;
    QLabel *label_3;
    QLineEdit *itemName_2;
    QPushButton *pushButton_2;
    QLabel *message_2;
    QPushButton *pushButton_6;
    QWidget *AddMember;
    QGroupBox *groupBox_17;
    QLineEdit *lineEdit_newName;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *lineEdit_newMemType;
    QLabel *label_6;
    QLineEdit *lineEdit_newExpDate;
    QLabel *label_7;
    QLabel *label_newMemStatus;
    QPushButton *pushButton_addFinish;
    QPushButton *pushButton_Exit;
    QSpinBox *addId;
    QWidget *RemoveMember;
    QGroupBox *groupBox_19;
    QLabel *label_8;
    QPushButton *pushButton_Delete;
    QLabel *label_deleted;
    QPushButton *pushButton_3;
    QSpinBox *deleteMember;
    QWidget *RecommendUpgrade;
    QGroupBox *groupBox_18;
    QTableView *tableView_11;
    QPushButton *pushButton_14;
    QWidget *Downgrade;
    QGroupBox *groupBox_20;
    QTableView *tableView_12;
    QPushButton *pushButton_15;
    QWidget *purchaseItem;
    QGroupBox *groupBox_21;
    QLabel *enterId;
    QLineEdit *itemEdit;
    QLabel *enterItem;
    QLabel *enterQty;
    QLabel *EnterDate;
    QLineEdit *dateEdit;
    QLabel *message_3;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QSpinBox *purchaseQuantity;
    QDoubleSpinBox *enterIdPurchase;
    QLabel *message_4;
    QLabel *message_5;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(855, 633);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(160, 90, 551, 421));
        SignIn = new QWidget();
        SignIn->setObjectName(QStringLiteral("SignIn"));
        groupBox = new QGroupBox(SignIn);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(130, 90, 281, 171));
        label_username = new QLabel(groupBox);
        label_username->setObjectName(QStringLiteral("label_username"));
        label_username->setGeometry(QRect(40, 50, 47, 13));
        label_password = new QLabel(groupBox);
        label_password->setObjectName(QStringLiteral("label_password"));
        label_password->setGeometry(QRect(40, 80, 47, 13));
        lineEdit_username = new QLineEdit(groupBox);
        lineEdit_username->setObjectName(QStringLiteral("lineEdit_username"));
        lineEdit_username->setGeometry(QRect(90, 50, 113, 20));
        lineEdit_username->setClearButtonEnabled(true);
        lineEdit_password = new QLineEdit(groupBox);
        lineEdit_password->setObjectName(QStringLiteral("lineEdit_password"));
        lineEdit_password->setGeometry(QRect(90, 80, 113, 20));
        lineEdit_password->setEchoMode(QLineEdit::Password);
        pushButton_login = new QPushButton(groupBox);
        pushButton_login->setObjectName(QStringLiteral("pushButton_login"));
        pushButton_login->setGeometry(QRect(100, 120, 75, 23));
        label_status = new QLabel(groupBox);
        label_status->setObjectName(QStringLiteral("label_status"));
        label_status->setGeometry(QRect(10, 140, 261, 21));
        label_status_2 = new QLabel(SignIn);
        label_status_2->setObjectName(QStringLiteral("label_status_2"));
        label_status_2->setGeometry(QRect(120, 260, 261, 16));
        stackedWidget->addWidget(SignIn);
        AdminBase = new QWidget();
        AdminBase->setObjectName(QStringLiteral("AdminBase"));
        groupBox_2 = new QGroupBox(AdminBase);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(140, 100, 271, 191));
        pushButton_members = new QPushButton(groupBox_2);
        pushButton_members->setObjectName(QStringLiteral("pushButton_members"));
        pushButton_members->setGeometry(QRect(20, 30, 101, 61));
        pushButton_inventory = new QPushButton(groupBox_2);
        pushButton_inventory->setObjectName(QStringLiteral("pushButton_inventory"));
        pushButton_inventory->setGeometry(QRect(150, 30, 101, 61));
        pushButton_memberships = new QPushButton(groupBox_2);
        pushButton_memberships->setObjectName(QStringLiteral("pushButton_memberships"));
        pushButton_memberships->setGeometry(QRect(20, 100, 101, 61));
        pushButton_logout_admin = new QPushButton(groupBox_2);
        pushButton_logout_admin->setObjectName(QStringLiteral("pushButton_logout_admin"));
        pushButton_logout_admin->setGeometry(QRect(190, 160, 75, 23));
        pushButton_purchase = new QPushButton(groupBox_2);
        pushButton_purchase->setObjectName(QStringLiteral("pushButton_purchase"));
        pushButton_purchase->setGeometry(QRect(150, 100, 101, 51));
        stackedWidget->addWidget(AdminBase);
        ManagerBase = new QWidget();
        ManagerBase->setObjectName(QStringLiteral("ManagerBase"));
        groupBox_3 = new QGroupBox(ManagerBase);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(100, 40, 331, 341));
        pushButton_sales = new QPushButton(groupBox_3);
        pushButton_sales->setObjectName(QStringLiteral("pushButton_sales"));
        pushButton_sales->setGeometry(QRect(20, 30, 141, 51));
        pushButton_purchases = new QPushButton(groupBox_3);
        pushButton_purchases->setObjectName(QStringLiteral("pushButton_purchases"));
        pushButton_purchases->setGeometry(QRect(20, 100, 141, 51));
        pushButton_qty = new QPushButton(groupBox_3);
        pushButton_qty->setObjectName(QStringLiteral("pushButton_qty"));
        pushButton_qty->setGeometry(QRect(20, 170, 141, 51));
        pushButton_rebates = new QPushButton(groupBox_3);
        pushButton_rebates->setObjectName(QStringLiteral("pushButton_rebates"));
        pushButton_rebates->setGeometry(QRect(20, 240, 141, 51));
        pushButton_expirations = new QPushButton(groupBox_3);
        pushButton_expirations->setObjectName(QStringLiteral("pushButton_expirations"));
        pushButton_expirations->setGeometry(QRect(170, 30, 141, 51));
        pushButton_item_lookup = new QPushButton(groupBox_3);
        pushButton_item_lookup->setObjectName(QStringLiteral("pushButton_item_lookup"));
        pushButton_item_lookup->setGeometry(QRect(170, 100, 141, 51));
        pushButton_member_lookup = new QPushButton(groupBox_3);
        pushButton_member_lookup->setObjectName(QStringLiteral("pushButton_member_lookup"));
        pushButton_member_lookup->setGeometry(QRect(170, 170, 141, 51));
        pushButton_convert = new QPushButton(groupBox_3);
        pushButton_convert->setObjectName(QStringLiteral("pushButton_convert"));
        pushButton_convert->setGeometry(QRect(170, 240, 141, 51));
        pushButton_logout_manager = new QPushButton(groupBox_3);
        pushButton_logout_manager->setObjectName(QStringLiteral("pushButton_logout_manager"));
        pushButton_logout_manager->setGeometry(QRect(240, 300, 75, 23));
        stackedWidget->addWidget(ManagerBase);
        ManagerMembers = new QWidget();
        ManagerMembers->setObjectName(QStringLiteral("ManagerMembers"));
        groupBox_4 = new QGroupBox(ManagerMembers);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 30, 511, 341));
        pushButton_back = new QPushButton(groupBox_4);
        pushButton_back->setObjectName(QStringLiteral("pushButton_back"));
        pushButton_back->setGeometry(QRect(430, 310, 75, 23));
        addMemberButton = new QPushButton(groupBox_4);
        addMemberButton->setObjectName(QStringLiteral("addMemberButton"));
        addMemberButton->setGeometry(QRect(10, 20, 121, 51));
        pushButton_4 = new QPushButton(groupBox_4);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(10, 80, 121, 51));
        tableView_8 = new QTableView(groupBox_4);
        tableView_8->setObjectName(QStringLiteral("tableView_8"));
        tableView_8->setGeometry(QRect(150, 20, 351, 281));
        stackedWidget->addWidget(ManagerMembers);
        ManageInventory = new QWidget();
        ManageInventory->setObjectName(QStringLiteral("ManageInventory"));
        groupBox_5 = new QGroupBox(ManageInventory);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(20, 20, 511, 371));
        pushButton_back_inventory = new QPushButton(groupBox_5);
        pushButton_back_inventory->setObjectName(QStringLiteral("pushButton_back_inventory"));
        pushButton_back_inventory->setGeometry(QRect(420, 330, 75, 23));
        pushButton_addItem = new QPushButton(groupBox_5);
        pushButton_addItem->setObjectName(QStringLiteral("pushButton_addItem"));
        pushButton_addItem->setGeometry(QRect(10, 20, 131, 51));
        pushButton_removeItem = new QPushButton(groupBox_5);
        pushButton_removeItem->setObjectName(QStringLiteral("pushButton_removeItem"));
        pushButton_removeItem->setGeometry(QRect(10, 80, 131, 51));
        tableView_9 = new QTableView(groupBox_5);
        tableView_9->setObjectName(QStringLiteral("tableView_9"));
        tableView_9->setGeometry(QRect(160, 20, 321, 291));
        stackedWidget->addWidget(ManageInventory);
        ManageMemberships = new QWidget();
        ManageMemberships->setObjectName(QStringLiteral("ManageMemberships"));
        groupBox_6 = new QGroupBox(ManageMemberships);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(40, 40, 451, 311));
        pushButton_back_memberships = new QPushButton(groupBox_6);
        pushButton_back_memberships->setObjectName(QStringLiteral("pushButton_back_memberships"));
        pushButton_back_memberships->setGeometry(QRect(350, 260, 75, 23));
        stackedWidget->addWidget(ManageMemberships);
        SalesReport = new QWidget();
        SalesReport->setObjectName(QStringLiteral("SalesReport"));
        groupBox_7 = new QGroupBox(SalesReport);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(20, 20, 511, 391));
        pushButton_back_report = new QPushButton(groupBox_7);
        pushButton_back_report->setObjectName(QStringLiteral("pushButton_back_report"));
        pushButton_back_report->setGeometry(QRect(420, 360, 75, 23));
        label_14 = new QLabel(groupBox_7);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 30, 81, 31));
        date_edit = new QLineEdit(groupBox_7);
        date_edit->setObjectName(QStringLiteral("date_edit"));
        date_edit->setGeometry(QRect(30, 60, 113, 20));
        pushButton_9 = new QPushButton(groupBox_7);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(40, 90, 75, 23));
        tableView_4 = new QTableView(groupBox_7);
        tableView_4->setObjectName(QStringLiteral("tableView_4"));
        tableView_4->setGeometry(QRect(170, 20, 321, 171));
        label_15 = new QLabel(groupBox_7);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(20, 280, 81, 20));
        totalrevenue = new QDoubleSpinBox(groupBox_7);
        totalrevenue->setObjectName(QStringLiteral("totalrevenue"));
        totalrevenue->setGeometry(QRect(30, 300, 101, 22));
        label_16 = new QLabel(groupBox_7);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 130, 141, 41));
        executive = new QSpinBox(groupBox_7);
        executive->setObjectName(QStringLiteral("executive"));
        executive->setGeometry(QRect(30, 160, 91, 22));
        label_17 = new QLabel(groupBox_7);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(20, 200, 141, 31));
        regular = new QSpinBox(groupBox_7);
        regular->setObjectName(QStringLiteral("regular"));
        regular->setGeometry(QRect(30, 230, 91, 22));
        pushButton_12 = new QPushButton(groupBox_7);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(140, 350, 111, 31));
        tableView_10 = new QTableView(groupBox_7);
        tableView_10->setObjectName(QStringLiteral("tableView_10"));
        tableView_10->setGeometry(QRect(170, 210, 321, 131));
        pushButton_16 = new QPushButton(groupBox_7);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(270, 350, 111, 31));
        stackedWidget->addWidget(SalesReport);
        TotPurchasesByNum = new QWidget();
        TotPurchasesByNum->setObjectName(QStringLiteral("TotPurchasesByNum"));
        groupBox_8 = new QGroupBox(TotPurchasesByNum);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(30, 20, 491, 381));
        pushButton_back_purchases = new QPushButton(groupBox_8);
        pushButton_back_purchases->setObjectName(QStringLiteral("pushButton_back_purchases"));
        pushButton_back_purchases->setGeometry(QRect(400, 340, 75, 23));
        LoadData = new QPushButton(groupBox_8);
        LoadData->setObjectName(QStringLiteral("LoadData"));
        LoadData->setGeometry(QRect(400, 50, 75, 31));
        tableView = new QTableView(groupBox_8);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(20, 50, 371, 271));
        label_9 = new QLabel(groupBox_8);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(160, 339, 61, 21));
        total = new QDoubleSpinBox(groupBox_8);
        total->setObjectName(QStringLiteral("total"));
        total->setGeometry(QRect(220, 340, 121, 22));
        stackedWidget->addWidget(TotPurchasesByNum);
        QtySold = new QWidget();
        QtySold->setObjectName(QStringLiteral("QtySold"));
        groupBox_9 = new QGroupBox(QtySold);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(50, 50, 431, 301));
        pushButton_back_qty = new QPushButton(groupBox_9);
        pushButton_back_qty->setObjectName(QStringLiteral("pushButton_back_qty"));
        pushButton_back_qty->setGeometry(QRect(340, 260, 75, 23));
        searchBox = new QLineEdit(groupBox_9);
        searchBox->setObjectName(QStringLiteral("searchBox"));
        searchBox->setGeometry(QRect(140, 70, 121, 31));
        label_21 = new QLabel(groupBox_9);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(140, 50, 121, 21));
        pushButton_13 = new QPushButton(groupBox_9);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(280, 80, 75, 23));
        label_23 = new QLabel(groupBox_9);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(70, 120, 111, 21));
        label_24 = new QLabel(groupBox_9);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(230, 120, 111, 16));
        qty = new QSpinBox(groupBox_9);
        qty->setObjectName(QStringLiteral("qty"));
        qty->setGeometry(QRect(70, 140, 111, 31));
        revenue_3 = new QDoubleSpinBox(groupBox_9);
        revenue_3->setObjectName(QStringLiteral("revenue_3"));
        revenue_3->setGeometry(QRect(230, 140, 111, 31));
        stackedWidget->addWidget(QtySold);
        Rebates = new QWidget();
        Rebates->setObjectName(QStringLiteral("Rebates"));
        groupBox_10 = new QGroupBox(Rebates);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(40, 30, 451, 361));
        pushButton_back_rebates = new QPushButton(groupBox_10);
        pushButton_back_rebates->setObjectName(QStringLiteral("pushButton_back_rebates"));
        pushButton_back_rebates->setGeometry(QRect(360, 320, 75, 23));
        tableView_6 = new QTableView(groupBox_10);
        tableView_6->setObjectName(QStringLiteral("tableView_6"));
        tableView_6->setGeometry(QRect(20, 20, 321, 321));
        pushButton_11 = new QPushButton(groupBox_10);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(350, 20, 91, 31));
        stackedWidget->addWidget(Rebates);
        MembExp = new QWidget();
        MembExp->setObjectName(QStringLiteral("MembExp"));
        groupBox_11 = new QGroupBox(MembExp);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setGeometry(QRect(20, 20, 501, 391));
        pushButton_back_expirations = new QPushButton(groupBox_11);
        pushButton_back_expirations->setObjectName(QStringLiteral("pushButton_back_expirations"));
        pushButton_back_expirations->setGeometry(QRect(420, 360, 75, 23));
        label_18 = new QLabel(groupBox_11);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(20, 40, 61, 21));
        month = new QLineEdit(groupBox_11);
        month->setObjectName(QStringLiteral("month"));
        month->setGeometry(QRect(20, 60, 113, 20));
        tableView_5 = new QTableView(groupBox_11);
        tableView_5->setObjectName(QStringLiteral("tableView_5"));
        tableView_5->setGeometry(QRect(155, 30, 331, 321));
        label_19 = new QLabel(groupBox_11);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 130, 121, 51));
        label_20 = new QLabel(groupBox_11);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(20, 240, 121, 31));
        textBrowser = new QTextBrowser(groupBox_11);
        textBrowser->setObjectName(QStringLiteral("textBrowser"));
        textBrowser->setGeometry(QRect(20, 270, 101, 31));
        textBrowser_2 = new QTextBrowser(groupBox_11);
        textBrowser_2->setObjectName(QStringLiteral("textBrowser_2"));
        textBrowser_2->setGeometry(QRect(20, 170, 101, 31));
        pushButton_10 = new QPushButton(groupBox_11);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(30, 90, 75, 23));
        listWidget = new QListWidget(groupBox_11);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(150, 30, 121, 321));
        listWidget_2 = new QListWidget(groupBox_11);
        listWidget_2->setObjectName(QStringLiteral("listWidget_2"));
        listWidget_2->setGeometry(QRect(270, 30, 111, 321));
        listWidget_3 = new QListWidget(groupBox_11);
        listWidget_3->setObjectName(QStringLiteral("listWidget_3"));
        listWidget_3->setGeometry(QRect(380, 30, 111, 321));
        stackedWidget->addWidget(MembExp);
        ItemLookup = new QWidget();
        ItemLookup->setObjectName(QStringLiteral("ItemLookup"));
        groupBox_12 = new QGroupBox(ItemLookup);
        groupBox_12->setObjectName(QStringLiteral("groupBox_12"));
        groupBox_12->setGeometry(QRect(20, 10, 501, 391));
        pushButton_back_item_lookup = new QPushButton(groupBox_12);
        pushButton_back_item_lookup->setObjectName(QStringLiteral("pushButton_back_item_lookup"));
        pushButton_back_item_lookup->setGeometry(QRect(410, 360, 75, 23));
        label_11 = new QLabel(groupBox_12);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 30, 71, 21));
        item_edit = new QLineEdit(groupBox_12);
        item_edit->setObjectName(QStringLiteral("item_edit"));
        item_edit->setGeometry(QRect(30, 50, 113, 20));
        pushButton_8 = new QPushButton(groupBox_12);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(40, 80, 75, 23));
        tableView_3 = new QTableView(groupBox_12);
        tableView_3->setObjectName(QStringLiteral("tableView_3"));
        tableView_3->setGeometry(QRect(160, 20, 321, 321));
        revenue = new QDoubleSpinBox(groupBox_12);
        revenue->setObjectName(QStringLiteral("revenue"));
        revenue->setGeometry(QRect(30, 220, 101, 22));
        label_12 = new QLabel(groupBox_12);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 200, 81, 20));
        label_13 = new QLabel(groupBox_12);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 130, 71, 21));
        sold = new QSpinBox(groupBox_12);
        sold->setObjectName(QStringLiteral("sold"));
        sold->setGeometry(QRect(30, 150, 81, 21));
        stackedWidget->addWidget(ItemLookup);
        MemberLookup = new QWidget();
        MemberLookup->setObjectName(QStringLiteral("MemberLookup"));
        groupBox_13 = new QGroupBox(MemberLookup);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(10, 20, 501, 381));
        pushButton_back_member_lookup = new QPushButton(groupBox_13);
        pushButton_back_member_lookup->setObjectName(QStringLiteral("pushButton_back_member_lookup"));
        pushButton_back_member_lookup->setGeometry(QRect(410, 340, 75, 23));
        search_edit = new QLineEdit(groupBox_13);
        search_edit->setObjectName(QStringLiteral("search_edit"));
        search_edit->setGeometry(QRect(30, 60, 113, 20));
        label_10 = new QLabel(groupBox_13);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 40, 111, 21));
        tableView_2 = new QTableView(groupBox_13);
        tableView_2->setObjectName(QStringLiteral("tableView_2"));
        tableView_2->setGeometry(QRect(160, 40, 321, 281));
        pushButton_7 = new QPushButton(groupBox_13);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(44, 90, 81, 23));
        stackedWidget->addWidget(MemberLookup);
        ConvertMembership = new QWidget();
        ConvertMembership->setObjectName(QStringLiteral("ConvertMembership"));
        groupBox_14 = new QGroupBox(ConvertMembership);
        groupBox_14->setObjectName(QStringLiteral("groupBox_14"));
        groupBox_14->setGeometry(QRect(120, 90, 321, 231));
        pushButton_back_convert = new QPushButton(groupBox_14);
        pushButton_back_convert->setObjectName(QStringLiteral("pushButton_back_convert"));
        pushButton_back_convert->setGeometry(QRect(240, 200, 75, 23));
        SearchMembUpgrade = new QPushButton(groupBox_14);
        SearchMembUpgrade->setObjectName(QStringLiteral("SearchMembUpgrade"));
        SearchMembUpgrade->setGeometry(QRect(70, 40, 171, 61));
        SearchMembDowngrade = new QPushButton(groupBox_14);
        SearchMembDowngrade->setObjectName(QStringLiteral("SearchMembDowngrade"));
        SearchMembDowngrade->setGeometry(QRect(70, 120, 171, 61));
        stackedWidget->addWidget(ConvertMembership);
        AddItem = new QWidget();
        AddItem->setObjectName(QStringLiteral("AddItem"));
        groupBox_15 = new QGroupBox(AddItem);
        groupBox_15->setObjectName(QStringLiteral("groupBox_15"));
        groupBox_15->setGeometry(QRect(100, 90, 351, 211));
        verticalLayoutWidget = new QWidget(groupBox_15);
        verticalLayoutWidget->setObjectName(QStringLiteral("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(90, 30, 171, 61));
        item = new QVBoxLayout(verticalLayoutWidget);
        item->setSpacing(6);
        item->setContentsMargins(11, 11, 11, 11);
        item->setObjectName(QStringLiteral("item"));
        item->setContentsMargins(0, 0, 0, 0);
        label = new QLabel(verticalLayoutWidget);
        label->setObjectName(QStringLiteral("label"));

        item->addWidget(label);

        itemName = new QLineEdit(verticalLayoutWidget);
        itemName->setObjectName(QStringLiteral("itemName"));

        item->addWidget(itemName);

        verticalLayoutWidget_2 = new QWidget(groupBox_15);
        verticalLayoutWidget_2->setObjectName(QStringLiteral("verticalLayoutWidget_2"));
        verticalLayoutWidget_2->setGeometry(QRect(90, 100, 171, 61));
        verticalLayout = new QVBoxLayout(verticalLayoutWidget_2);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        label_2 = new QLabel(verticalLayoutWidget_2);
        label_2->setObjectName(QStringLiteral("label_2"));

        verticalLayout->addWidget(label_2);

        addItemPrice = new QDoubleSpinBox(verticalLayoutWidget_2);
        addItemPrice->setObjectName(QStringLiteral("addItemPrice"));
        addItemPrice->setButtonSymbols(QAbstractSpinBox::NoButtons);
        addItemPrice->setMaximum(999999);

        verticalLayout->addWidget(addItemPrice);

        message = new QLabel(groupBox_15);
        message->setObjectName(QStringLiteral("message"));
        message->setGeometry(QRect(10, 170, 131, 31));
        pushButton = new QPushButton(groupBox_15);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(140, 170, 81, 31));
        pushButton_5 = new QPushButton(groupBox_15);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(270, 10, 75, 23));
        stackedWidget->addWidget(AddItem);
        RemoveItem = new QWidget();
        RemoveItem->setObjectName(QStringLiteral("RemoveItem"));
        groupBox_16 = new QGroupBox(RemoveItem);
        groupBox_16->setObjectName(QStringLiteral("groupBox_16"));
        groupBox_16->setGeometry(QRect(100, 140, 331, 161));
        verticalLayoutWidget_3 = new QWidget(groupBox_16);
        verticalLayoutWidget_3->setObjectName(QStringLiteral("verticalLayoutWidget_3"));
        verticalLayoutWidget_3->setGeometry(QRect(80, 40, 171, 61));
        item_2 = new QVBoxLayout(verticalLayoutWidget_3);
        item_2->setSpacing(6);
        item_2->setContentsMargins(11, 11, 11, 11);
        item_2->setObjectName(QStringLiteral("item_2"));
        item_2->setContentsMargins(0, 0, 0, 0);
        label_3 = new QLabel(verticalLayoutWidget_3);
        label_3->setObjectName(QStringLiteral("label_3"));

        item_2->addWidget(label_3);

        itemName_2 = new QLineEdit(verticalLayoutWidget_3);
        itemName_2->setObjectName(QStringLiteral("itemName_2"));

        item_2->addWidget(itemName_2);

        pushButton_2 = new QPushButton(groupBox_16);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(110, 120, 101, 23));
        message_2 = new QLabel(groupBox_16);
        message_2->setObjectName(QStringLiteral("message_2"));
        message_2->setGeometry(QRect(10, 120, 131, 31));
        pushButton_6 = new QPushButton(groupBox_16);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(250, 10, 75, 23));
        stackedWidget->addWidget(RemoveItem);
        AddMember = new QWidget();
        AddMember->setObjectName(QStringLiteral("AddMember"));
        groupBox_17 = new QGroupBox(AddMember);
        groupBox_17->setObjectName(QStringLiteral("groupBox_17"));
        groupBox_17->setGeometry(QRect(40, 50, 381, 271));
        lineEdit_newName = new QLineEdit(groupBox_17);
        lineEdit_newName->setObjectName(QStringLiteral("lineEdit_newName"));
        lineEdit_newName->setGeometry(QRect(180, 50, 113, 20));
        label_4 = new QLabel(groupBox_17);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 50, 47, 13));
        label_5 = new QLabel(groupBox_17);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 90, 91, 16));
        lineEdit_newMemType = new QLineEdit(groupBox_17);
        lineEdit_newMemType->setObjectName(QStringLiteral("lineEdit_newMemType"));
        lineEdit_newMemType->setGeometry(QRect(180, 130, 113, 20));
        label_6 = new QLabel(groupBox_17);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 130, 111, 16));
        lineEdit_newExpDate = new QLineEdit(groupBox_17);
        lineEdit_newExpDate->setObjectName(QStringLiteral("lineEdit_newExpDate"));
        lineEdit_newExpDate->setGeometry(QRect(180, 170, 113, 20));
        label_7 = new QLabel(groupBox_17);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 170, 141, 16));
        label_newMemStatus = new QLabel(groupBox_17);
        label_newMemStatus->setObjectName(QStringLiteral("label_newMemStatus"));
        label_newMemStatus->setGeometry(QRect(20, 240, 111, 21));
        pushButton_addFinish = new QPushButton(groupBox_17);
        pushButton_addFinish->setObjectName(QStringLiteral("pushButton_addFinish"));
        pushButton_addFinish->setGeometry(QRect(180, 220, 111, 31));
        pushButton_Exit = new QPushButton(groupBox_17);
        pushButton_Exit->setObjectName(QStringLiteral("pushButton_Exit"));
        pushButton_Exit->setGeometry(QRect(300, 10, 75, 23));
        addId = new QSpinBox(groupBox_17);
        addId->setObjectName(QStringLiteral("addId"));
        addId->setGeometry(QRect(180, 90, 111, 20));
        addId->setButtonSymbols(QAbstractSpinBox::NoButtons);
        addId->setMaximum(99999999);
        stackedWidget->addWidget(AddMember);
        RemoveMember = new QWidget();
        RemoveMember->setObjectName(QStringLiteral("RemoveMember"));
        groupBox_19 = new QGroupBox(RemoveMember);
        groupBox_19->setObjectName(QStringLiteral("groupBox_19"));
        groupBox_19->setGeometry(QRect(150, 120, 281, 131));
        label_8 = new QLabel(groupBox_19);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(20, 40, 181, 31));
        pushButton_Delete = new QPushButton(groupBox_19);
        pushButton_Delete->setObjectName(QStringLiteral("pushButton_Delete"));
        pushButton_Delete->setGeometry(QRect(160, 60, 81, 31));
        label_deleted = new QLabel(groupBox_19);
        label_deleted->setObjectName(QStringLiteral("label_deleted"));
        label_deleted->setGeometry(QRect(10, 100, 191, 21));
        pushButton_3 = new QPushButton(groupBox_19);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(200, 10, 75, 23));
        deleteMember = new QSpinBox(groupBox_19);
        deleteMember->setObjectName(QStringLiteral("deleteMember"));
        deleteMember->setGeometry(QRect(20, 70, 121, 20));
        deleteMember->setButtonSymbols(QAbstractSpinBox::NoButtons);
        deleteMember->setMaximum(99999999);
        stackedWidget->addWidget(RemoveMember);
        RecommendUpgrade = new QWidget();
        RecommendUpgrade->setObjectName(QStringLiteral("RecommendUpgrade"));
        groupBox_18 = new QGroupBox(RecommendUpgrade);
        groupBox_18->setObjectName(QStringLiteral("groupBox_18"));
        groupBox_18->setGeometry(QRect(40, 20, 501, 381));
        tableView_11 = new QTableView(groupBox_18);
        tableView_11->setObjectName(QStringLiteral("tableView_11"));
        tableView_11->setGeometry(QRect(10, 40, 481, 281));
        pushButton_14 = new QPushButton(groupBox_18);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(390, 340, 75, 23));
        stackedWidget->addWidget(RecommendUpgrade);
        Downgrade = new QWidget();
        Downgrade->setObjectName(QStringLiteral("Downgrade"));
        groupBox_20 = new QGroupBox(Downgrade);
        groupBox_20->setObjectName(QStringLiteral("groupBox_20"));
        groupBox_20->setGeometry(QRect(20, 20, 501, 381));
        tableView_12 = new QTableView(groupBox_20);
        tableView_12->setObjectName(QStringLiteral("tableView_12"));
        tableView_12->setGeometry(QRect(10, 40, 481, 281));
        pushButton_15 = new QPushButton(groupBox_20);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(390, 340, 75, 23));
        stackedWidget->addWidget(Downgrade);
        purchaseItem = new QWidget();
        purchaseItem->setObjectName(QStringLiteral("purchaseItem"));
        groupBox_21 = new QGroupBox(purchaseItem);
        groupBox_21->setObjectName(QStringLiteral("groupBox_21"));
        groupBox_21->setGeometry(QRect(70, 30, 461, 341));
        enterId = new QLabel(groupBox_21);
        enterId->setObjectName(QStringLiteral("enterId"));
        enterId->setGeometry(QRect(40, 40, 47, 13));
        itemEdit = new QLineEdit(groupBox_21);
        itemEdit->setObjectName(QStringLiteral("itemEdit"));
        itemEdit->setGeometry(QRect(90, 120, 113, 20));
        enterItem = new QLabel(groupBox_21);
        enterItem->setObjectName(QStringLiteral("enterItem"));
        enterItem->setGeometry(QRect(26, 120, 51, 20));
        enterQty = new QLabel(groupBox_21);
        enterQty->setObjectName(QStringLiteral("enterQty"));
        enterQty->setGeometry(QRect(16, 160, 71, 20));
        EnterDate = new QLabel(groupBox_21);
        EnterDate->setObjectName(QStringLiteral("EnterDate"));
        EnterDate->setGeometry(QRect(20, 80, 81, 16));
        dateEdit = new QLineEdit(groupBox_21);
        dateEdit->setObjectName(QStringLiteral("dateEdit"));
        dateEdit->setGeometry(QRect(90, 80, 113, 20));
        message_3 = new QLabel(groupBox_21);
        message_3->setObjectName(QStringLiteral("message_3"));
        message_3->setGeometry(QRect(160, 280, 131, 31));
        pushButton_17 = new QPushButton(groupBox_21);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(140, 200, 151, 71));
        pushButton_18 = new QPushButton(groupBox_21);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(360, 300, 75, 23));
        pushButton_19 = new QPushButton(groupBox_21);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(280, 40, 75, 23));
        pushButton_20 = new QPushButton(groupBox_21);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(280, 120, 75, 23));
        purchaseQuantity = new QSpinBox(groupBox_21);
        purchaseQuantity->setObjectName(QStringLiteral("purchaseQuantity"));
        purchaseQuantity->setGeometry(QRect(90, 160, 111, 20));
        purchaseQuantity->setButtonSymbols(QAbstractSpinBox::NoButtons);
        purchaseQuantity->setMaximum(999999);
        enterIdPurchase = new QDoubleSpinBox(groupBox_21);
        enterIdPurchase->setObjectName(QStringLiteral("enterIdPurchase"));
        enterIdPurchase->setGeometry(QRect(90, 40, 111, 22));
        enterIdPurchase->setButtonSymbols(QAbstractSpinBox::NoButtons);
        enterIdPurchase->setDecimals(0);
        enterIdPurchase->setMaximum(1e+8);
        message_4 = new QLabel(groupBox_21);
        message_4->setObjectName(QStringLiteral("message_4"));
        message_4->setGeometry(QRect(260, 70, 131, 31));
        message_5 = new QLabel(groupBox_21);
        message_5->setObjectName(QStringLiteral("message_5"));
        message_5->setGeometry(QRect(260, 160, 131, 31));
        stackedWidget->addWidget(purchaseItem);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 855, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(6);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("MainWindow", "Signin", Q_NULLPTR));
        label_username->setText(QApplication::translate("MainWindow", "Username", Q_NULLPTR));
        label_password->setText(QApplication::translate("MainWindow", "Password", Q_NULLPTR));
        pushButton_login->setText(QApplication::translate("MainWindow", "Login", Q_NULLPTR));
        label_status->setText(QString());
        label_status_2->setText(QString());
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Admin", Q_NULLPTR));
        pushButton_members->setText(QApplication::translate("MainWindow", "Manage members", Q_NULLPTR));
        pushButton_inventory->setText(QApplication::translate("MainWindow", "Manage inventory", Q_NULLPTR));
        pushButton_memberships->setText(QApplication::translate("MainWindow", "Memberships", Q_NULLPTR));
        pushButton_logout_admin->setText(QApplication::translate("MainWindow", "Logout", Q_NULLPTR));
        pushButton_purchase->setText(QApplication::translate("MainWindow", "Purchase Item", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Manager", Q_NULLPTR));
        pushButton_sales->setText(QApplication::translate("MainWindow", "Sales report (day)", Q_NULLPTR));
        pushButton_purchases->setText(QApplication::translate("MainWindow", "Total purchases by number", Q_NULLPTR));
        pushButton_qty->setText(QApplication::translate("MainWindow", "Qty sold by item name", Q_NULLPTR));
        pushButton_rebates->setText(QApplication::translate("MainWindow", "Rebates", Q_NULLPTR));
        pushButton_expirations->setText(QApplication::translate("MainWindow", "Membership expirations", Q_NULLPTR));
        pushButton_item_lookup->setText(QApplication::translate("MainWindow", "Item lookup", Q_NULLPTR));
        pushButton_member_lookup->setText(QApplication::translate("MainWindow", "Member lookup", Q_NULLPTR));
        pushButton_convert->setText(QApplication::translate("MainWindow", "Convert membership", Q_NULLPTR));
        pushButton_logout_manager->setText(QApplication::translate("MainWindow", "Logout", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Admin: Manage Members", Q_NULLPTR));
        pushButton_back->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        addMemberButton->setText(QApplication::translate("MainWindow", "Add New Member", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("MainWindow", "Delete Member", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "Admin: Manage Inventory", Q_NULLPTR));
        pushButton_back_inventory->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        pushButton_addItem->setText(QApplication::translate("MainWindow", "Add Item", Q_NULLPTR));
        pushButton_removeItem->setText(QApplication::translate("MainWindow", "Remove Item", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Admin: Manage Memberships", Q_NULLPTR));
        pushButton_back_memberships->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "Manager: Sales Report", Q_NULLPTR));
        pushButton_back_report->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "Enter Date", Q_NULLPTR));
        date_edit->setText(QApplication::translate("MainWindow", "MM/DD/YYYY", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("MainWindow", "Search", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "Total Revenue", Q_NULLPTR));
        label_16->setText(QApplication::translate("MainWindow", "Executive members shopped", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "Regular members shopped", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("MainWindow", "Sort by Executive", Q_NULLPTR));
        pushButton_16->setText(QApplication::translate("MainWindow", "Sort by Regular", Q_NULLPTR));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "Manager: Total Purchases sorted by number", Q_NULLPTR));
        pushButton_back_purchases->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        LoadData->setText(QApplication::translate("MainWindow", "Load Data", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "Grand Total", Q_NULLPTR));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "Manager: Quantity sold by item name", Q_NULLPTR));
        pushButton_back_qty->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        label_21->setText(QApplication::translate("MainWindow", "Enter search item", Q_NULLPTR));
        pushButton_13->setText(QApplication::translate("MainWindow", "Enter", Q_NULLPTR));
        label_23->setText(QApplication::translate("MainWindow", "Total quantity", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "Total revenue", Q_NULLPTR));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "Manager: Rebates", Q_NULLPTR));
        pushButton_back_rebates->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        pushButton_11->setText(QApplication::translate("MainWindow", "Load Data", Q_NULLPTR));
        groupBox_11->setTitle(QApplication::translate("MainWindow", "Manager: Manage membership expirations", Q_NULLPTR));
        pushButton_back_expirations->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "Enter Month", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "Cost to renew Executive", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "Cost to renew Regular", Q_NULLPTR));
        textBrowser->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">$65.00</span></p></body></html>", Q_NULLPTR));
        textBrowser_2->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">$120.00</span></p></body></html>", Q_NULLPTR));
        pushButton_10->setText(QApplication::translate("MainWindow", "Search", Q_NULLPTR));
        groupBox_12->setTitle(QApplication::translate("MainWindow", "Manager: Item Lookup", Q_NULLPTR));
        pushButton_back_item_lookup->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "Enter Item", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("MainWindow", "Search", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "Total Revenue", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "Total Sold", Q_NULLPTR));
        groupBox_13->setTitle(QApplication::translate("MainWindow", "Manager: Member Lookup", Q_NULLPTR));
        pushButton_back_member_lookup->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "Enter Name or ID", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("MainWindow", "Search", Q_NULLPTR));
        groupBox_14->setTitle(QApplication::translate("MainWindow", "Manager: Convert Membership", Q_NULLPTR));
        pushButton_back_convert->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        SearchMembUpgrade->setText(QApplication::translate("MainWindow", "Search Members for Upgrade", Q_NULLPTR));
        SearchMembDowngrade->setText(QApplication::translate("MainWindow", "Search Members for Downgrade", Q_NULLPTR));
        groupBox_15->setTitle(QApplication::translate("MainWindow", "Add Item", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "Item Name", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "Price", Q_NULLPTR));
        message->setText(QString());
        pushButton->setText(QApplication::translate("MainWindow", "Add Item", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("MainWindow", "Exit", Q_NULLPTR));
        groupBox_16->setTitle(QApplication::translate("MainWindow", "Remove Item", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "Item Name", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("MainWindow", "Delete Item", Q_NULLPTR));
        message_2->setText(QString());
        pushButton_6->setText(QApplication::translate("MainWindow", "Exit", Q_NULLPTR));
        groupBox_17->setTitle(QApplication::translate("MainWindow", "Add New Member", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "NAME", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "MEMBER TYPE", Q_NULLPTR));
        lineEdit_newExpDate->setText(QApplication::translate("MainWindow", "EX. MM/DD/YYYY", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "EXP. DATE", Q_NULLPTR));
        label_newMemStatus->setText(QString());
        pushButton_addFinish->setText(QApplication::translate("MainWindow", "Add Member", Q_NULLPTR));
        pushButton_Exit->setText(QApplication::translate("MainWindow", "Exit", Q_NULLPTR));
        groupBox_19->setTitle(QApplication::translate("MainWindow", "Admin: delete member", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "Enter member ID to delete", Q_NULLPTR));
        pushButton_Delete->setText(QApplication::translate("MainWindow", "Delete", Q_NULLPTR));
        label_deleted->setText(QString());
        pushButton_3->setText(QApplication::translate("MainWindow", "Exit", Q_NULLPTR));
        groupBox_18->setTitle(QApplication::translate("MainWindow", "Upgrade Recommendations", Q_NULLPTR));
        pushButton_14->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        groupBox_20->setTitle(QApplication::translate("MainWindow", "Downgrade Recommendations", Q_NULLPTR));
        pushButton_15->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        groupBox_21->setTitle(QApplication::translate("MainWindow", "Admin: Purchase Item", Q_NULLPTR));
        enterId->setText(QApplication::translate("MainWindow", "Enter id", Q_NULLPTR));
        enterItem->setText(QApplication::translate("MainWindow", "Enter Item", Q_NULLPTR));
        enterQty->setText(QApplication::translate("MainWindow", "Enter Quantity", Q_NULLPTR));
        EnterDate->setText(QApplication::translate("MainWindow", "Enter Date", Q_NULLPTR));
        message_3->setText(QString());
        pushButton_17->setText(QApplication::translate("MainWindow", "Purchase Item", Q_NULLPTR));
        pushButton_18->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        pushButton_19->setText(QApplication::translate("MainWindow", "Check ID", Q_NULLPTR));
        pushButton_20->setText(QApplication::translate("MainWindow", "Check Item", Q_NULLPTR));
        message_4->setText(QString());
        message_5->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
